[build]
  command   = "npm ci --legacy-peer-deps && npm run build"
  publish   = "dist/multi-step-form-main/browser"

[build.environment]
  # optional but helps future you remember
  NPM_FLAGS = "--legacy-peer-deps"